--- 
deployment:
	tasks:
		- export DEPLOYPATH=/home2/premierh/payroll.premierhotelibadan.com
		- /bin/cp index.html $DEPLOYPATH
		- /bin/cp style.css $DEPLOYPATH


ssh://premierh@premierhotelibadan.com/home2/premierh/payroll.premierhotelibadan.com

git push cpanel


name: Publish Premier Payroll 
on:
	push: 
		branches: 
			- main 

jobs: 
	FTP-Deploy-Action:
		name: FTP-Deploy-Action 
		runs-on: ubuntu-latest
		steps: 
			-uses: actions/checkout@v2.1.0
			 with:
				fetch-depth: 2 
			- name: FTP-Deploy-Action 
			  uses: SamKirkland/FTP-Deploy-Action@3.1.1
			  with: 
				ftp-server:${{ secrets.FTP_SERVER }}
				ftp-username: ${{ secrets.FTP_USERNAME }} 
				ftp-password: ${{ secrets.FTP_PASSWORD }}
